placement_activities/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pmt_act.urls','pmt_act'),namespace='pmt_act')),
    path('users/', include(('users.urls','users'),namespace='users')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

pmt_act/urls.py
"""Define URL Patterns for pmt_act"""

from django.urls import path

from . import views

urlpatterns = [
    #Home Page
    path('',views.index,name='index'),
    
    #page for viewing all trainings/workshops
    path('trainings_workshops/',views.trainings_workshops,
        name='trainings_workshops'),

    #page for viewing details of a single training/workshop
    path('trainings_workshops/<int:training_workshop_id>/',
        views.training_workshop,name='training_workshop'),
    
    #page for adding a new training/workshop
    path('new_tw/',views.new_tw, name='new_tw'),
    
    #page for editing a training/workshop
    path('edit_tw/<int:detail_id>/',
        views.edit_tw,name='edit_tw'),
        
    #page for deleting a training/workshop
    path('delete_tw/<int:detail_id>/',
        views.delete_tw,name='delete_tw'),

    #page for enrolling a training/workshop
    path('enroll_tw/<int:detail_id>/',
        views.enroll_tw,name='enroll_tw'),
]

users/urls.py
"""Define URL Patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    #login page
    path('login/', 
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
    
    #Logout page
    path('logout/', views.logout_view, name='logout'),
    
    #Registration page
    path('register/', views.register, name='register'),
]

pmt_act/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

class Trainings_Workshops(models.Model):
    """New Trainings/Workshops where students can register."""
    
    class Meta:
        verbose_name='Training/Workshop'
        verbose_name_plural='Trainings/Workshops'
        
    name = models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(upload_to = 'banners/',null=True,
    blank=True)
    
    registration_Begins=models.DateTimeField(blank=False,null=True)
    registration_Ends=models.DateTimeField(blank=False,null=True)
    event_Begins=models.DateTimeField(blank=False,null=True)
    event_Fee=models.DecimalField(max_digits=7,decimal_places=2,
        blank=False,null=True)
    event_URL=models.URLField(null=True,blank=True)
    additional_Details=models.TextField(null=True,blank=True)
    contact_Name=models.CharField(max_length=50,blank=False,null=True)
    contact_Email=models.EmailField(blank=False,null=True)
    contact_No=PhoneNumberField(blank=False,null=True,
        unique=False)
    document=models.FileField(upload_to='document/',blank=True,
        null=True)
    valid = models.BooleanField(default=False,blank=False)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,
        null=False,default=1)
    
    def __str__(self):
        """return a string representation of the model"""
        return self.name

class Enroll_TW(models.Model):
    """Enroll Trainings/Workshops where students can register."""
    
    tw_id = models.ForeignKey(Trainings_Workshops,on_delete=models.CASCADE,blank=False,
        null=False,unique=False)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,blank=False,
        null=False,unique=False)
    enrolled = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural='Enroll_TW'
        unique_together = (('user_id', 'tw_id'),)
    
    def __str__(self):
        """return a string representation of the model"""
        return ("User: " + str(self.user_id) + " enrolled to " 
            + "Training/Workshop: " + str(self.tw_id))

pmt_act/forms.py
from django import forms

from .models import Trainings_Workshops,Enroll_TW

class TWForm(forms.ModelForm):
    
    class Meta:
        model = Trainings_Workshops
        fields = '__all__'
        help_texts = {'registration_Begins':'(Use Format:YYYY-MM-DD HH:MM:SS)',
            'registration_Ends':'(Use Format:YYYY-MM-DD HH:MM:SS)',
            'event_Begins':'(Use Format:YYYY-MM-DD HH:MM:SS)'}
        initial = {'owner':'admin'}
        widgets = {'registration_Begins':forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'registration_Ends':forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'event_Begins':forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'valid': forms.HiddenInput(),'owner': forms.HiddenInput()}

class EnrollTWForm(forms.ModelForm):
    
    class Meta:
        model = Enroll_TW
        fields = '__all__'
        widgets = {'user_id': forms.HiddenInput(),
            'tw_id_id': forms.HiddenInput()}

pmt_act/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django import forms
import psycopg2


from .models import Trainings_Workshops,Enroll_TW
from .forms import TWForm,EnrollTWForm

def index(request):
    """The home page for pmt_act"""
    return render(request,'pmt_act/index.html')
    
@login_required    
def trainings_workshops(request):
    """Show all trainings_workshops."""
    trainings_workshops=Trainings_Workshops.objects.order_by('date_added')
    context={'trainings_workshops':trainings_workshops} 
    return render(request,'pmt_act/trainings_workshops.html',context)

@login_required
def training_workshop(request,training_workshop_id):
    """Show about a single training_workshop"""
    ps_connect=psycopg2.connect(user="admin",
                                  password="rootadmin",
                                  host="localhost",
                                  port="5432",
                                  database="pmt_act")
    cursor=ps_connect.cursor()
    detail=get_object_or_404(Trainings_Workshops,id=training_workshop_id)
    count=cursor.callproc('"countEnrolledUsers"',(detail.id,))
    result=cursor.fetchall()
    cursor.close()
    context={'detail':detail,'count':result[0][0]} 
    return render(request,'pmt_act/training_workshop.html',context)

@login_required
def new_tw(request):
    """Add a new Training/Workshop"""
    if request.method != 'POST':
        #No data submitted so create a blank form
        form = TWForm()
    else:
        #POST data submitted so process data
        form=TWForm(request.POST,request.FILES)
        if form.is_valid():
            new_tw=form.save(commit=False)
            new_tw.owner=request.user
            new_tw.save()
            return HttpResponseRedirect(reverse('pmt_act:trainings_workshops'))
            
    context={'form':form}
    return render(request,'pmt_act/new_tw.html',context)

@login_required
def edit_tw(request,detail_id):
    """Edit an existing entry"""
    
    tw=Trainings_Workshops.objects.get(id=detail_id)
    if tw.owner != request.user:
        raise Http404
    if request.method != 'POST':
        #Inintially, the form is filled with current tw.
        form = TWForm(instance=tw)
    else:
        #POST data submitted so process data
        form=TWForm(request.POST, request.FILES, instance=tw)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('pmt_act:training_workshop',args=[detail_id]))
            
    context={'tw':tw,'form':form}
    return render(request,'pmt_act/edit_tw.html',context)
    
@login_required
def delete_tw(request,detail_id):
    """Delete an existing entry"""
    
    tw=Trainings_Workshops.objects.get(id=detail_id)
    
    if tw.owner != request.user:
        raise Http404
    
    if request.method == 'POST':
        if 'confirm' in request.POST:
            tw.delete()
            return HttpResponseRedirect(reverse('pmt_act:trainings_workshops'))
        
        elif 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('pmt_act:training_workshop',args=[detail_id]))

    context={'tw':tw}
    return render(request,'pmt_act/delete_tw.html',context)

@login_required
def enroll_tw(request,detail_id):
    """Enroll an existing entry"""
    
    tw=Trainings_Workshops.objects.get(id=detail_id)
    if Enroll_TW.objects.filter(tw_id=detail_id,user_id=request.user).count()<1:
        enroll_tw=Enroll_TW.objects.create(tw_id=tw,user_id=request.user,enrolled=False)
    else:
        enroll_tw=Enroll_TW.objects.get(tw_id=detail_id,user_id=request.user)
    
    if request.method == 'POST':
        if 'confirmEn' in request.POST:
            enroll_tw=Enroll_TW.objects.filter(tw_id=tw,user_id=request.user).update(enrolled=True)
            form=EnrollTWForm(request.POST)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(reverse('pmt_act:trainings_workshops'))
                
        elif 'cancelEn' in request.POST:
            return HttpResponseRedirect(reverse('pmt_act:training_workshop',args=[detail_id]))
            
        elif 'goBack' in request.POST:
            return HttpResponseRedirect(reverse('pmt_act:trainings_workshops'))
            
    context={'tw':tw,'enroll_tw':enroll_tw}
    return render(request,'pmt_act/enroll_tw.html',context)

pmt_act/templates/pmt_act/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<title>Placement Activities</title>
		
		{% bootstrap_css %}
		{% bootstrap_javascript %}
	  
		<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
		<link href="/assets/css/style1.css" rel="stylesheet">
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
		<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
		<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
		<script>			
			$(function () {
				$('.datetime-input').datetimepicker({
					format:'YYYY-MM-DD HH:mm:ss'
				});
			});
		</script>
	</head>
	
	<body class="img-bg">
		
		<!-- Static navbar -->
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
			
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed"
						data-toggle="collapse" data-target="#navbar"
						aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'pmt_act:index' %}">Placement Activities</a>
				</div>
				
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav text1">
						<li><a href="{% url 'pmt_act:trainings_workshops' %}">Trainings/Workshops</a></li>
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li><a>Hello, {{ user.username }}.</a></li>
							<li><a href="{% url 'users:logout' %}">Log Out</a></li>
						{% else %}
							<li><a href="{% url 'users:register' %}">Register</a></li>
							<li><a href="{% url 'users:login' %}">Log In</a></li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse -->
				
			</div>
		</nav>
		
		<div class="container">
		
			<div class="page-header">
				{% block header %}{% endblock header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
			
		</div><!-- /container -->
	</body>
</html>

pmt_act/templates/pmt_act/delete_tw.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	{% if tw.valid == True %}
		<h2 class='animated infinite flash delay-0s' style='color:rgb(230, 0, 0)'><b>WARNING!!<b></h2>
	{% endif %}
{% endblock header %}

{% block content %}
	{% if tw.valid == True %}
		<h3 class='animated 1 fadeIn delay-1s'><b>Are you sure you want to delete Training/Workshop: {{ tw.name }}</b>?</h3>
		
		<form action="{% url 'pmt_act:delete_tw' tw.id %}" method='post' class="form animated 1 fadeIn delay-2s" enctype="multipart/form-data">
		
		{% csrf_token %}
		
		{% buttons %}
			<button type='submit' name="confirm" class="btn btn-primary animated 1 bounceIn delay-2s">Confirm</button>
			<button type='submit' name="cancel" class="btn btn-primary animated 1 bounceIn delay-2s">Cancel</button>
		{% endbuttons %}
		
		</form>
	{% endif %}
{% endblock content %}

pmt_act/templates/pmt_act/edit_tw.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}
{% block header %}
	{% if tw.valid == True %}
		<h2 class='animated 1 fadeInUp delay-0s'>Edit Training/Workshop:</h2>
	{% endif %}
	{% endblock header %}

{% block content %}
	{% if tw.valid == True %}
	
		<form action="{% url 'pmt_act:edit_tw' tw.id %}" method='post' class="form animated 1 fadeIn delay-1s" enctype="multipart/form-data">
			
			{% csrf_token %}
			{% bootstrap_form form %}
			
			{% buttons %}
				<button name="submit" class="btn btn-primary animated 1 bounceIn delay-2s">Save Changes</button>
			{% endbuttons %}
		
		</form>
	
	{% endif %}
{% endblock content %}

pmt_act/templates/pmt_act/enroll_tw.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	{% if tw.valid == True %}	
		<h2 class='animated infinite flash delay-0s' style='color:rgb(0, 230, 0)'><b>CONFIRMATION!!<b></h2>
	{% endif %}	
{% endblock header %}

{% block content %}
	{% if tw.valid == True %}
	
		{% if enroll_tw.user_id.id == user.id and enroll_tw.enrolled == True %}

			<h3 class='animated 1 fadeIn delay-1s'><b>{{ user }}, you are already enrolled for Training/Workshop: {{ tw.name }}</b></h3>
			
			<form action="{% url 'pmt_act:enroll_tw' tw.id %}" method='post' class="form animated 1 fadeIn delay-2s" enctype="multipart/form-data">
			
			{% csrf_token %}
			
			{% buttons %}
				<button type='submit' name="goBack" class="btn btn-primary animated 1 bounceIn delay-2s">Go Back To Trainings/Workshops</button>

			{% endbuttons %}
			
			</form>
			
		{% else %}
		
			<h3 class='animated 1 fadeIn delay-1s'><b>{{ user }}, confirm your enrollment for Training/Workshop: {{ tw.name }}</b></h3>
			
			<form action="{% url 'pmt_act:enroll_tw' tw.id %}" method='post' class="form animated 1 fadeIn delay-2s" enctype="multipart/form-data">
			
			{% csrf_token %}
			
			{% buttons %}
				<button type='submit' name="confirmEn" class="btn btn-primary animated 1 bounceIn delay-2s">Confirm</button>
				<button type='submit' name="cancelEn" class="btn btn-primary animated 1 bounceIn delay-2s">Cancel</button>
			{% endbuttons %}
			
			</form>
		
		{% endif %}
	
	{% endif %}
{% endblock content %}
	

pmt_act/templates/pmt_act/index.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<div class='jumbotron animated 1 fadeIn delay-1s' style='opacity:0.6'>
		<h1 class='animated 1 fadeInUp delay-1s'>GET YOUR DREAM JOB.</h1>
		<img class="myImages animated 1 fadeIn delay-0s" src='/assets/img/img-slide-1.jpg'style="width:100%;height:50vh;">
		<img class="myImages animated 1 fadeIn delay-0s" src='/assets/img/img-slide-2.jpg' style="width:100%;height:50vh;">
		<img class="myImages animated 1 fadeIn delay-0s" src='/assets/img/img-slide-3.jpg' style="width:100%;height:50vh;">
		<img class="myImages animated 1 fadeIn delay-0s" src='/assets/img/img-slide-4.jpg'style="width:100%;height:50vh;">
		<script>
			var myIndex = 0;

			function carousel() {
				var i;
				var x = document.getElementsByClassName("myImages");
				for (i = 0; i < x.length; i++) {
					x[i].style.display ="none";  
				}
				myIndex++;
				if (myIndex > x.length) {myIndex = 1}    
				x[myIndex-1].style.display = "block";  
				setTimeout(carousel, 2500);    
			}
			
			carousel();
		</script>
	</div>
{% endblock header %}

{% block content %}
	<h2 class='animated 1 fadeIn delay-2s'>
		{% if user.is_authenticated %}
			{{ user }},
		{% else %}
			<a href="{% url 'users:register' %}">Register Yourself</a> to
		{% endif %}
		get the latest updates
		about the placement activities so that you don't miss any opportunities
		and climb your way up for your dream job.
	</h2>
	<h2 class='animated 1 fadeIn delay-3s'>Share your knowledge of placement related events with others and
	rise up together for building a bright career. 
	Remember knowlegde always grows through sharing! </h2>
{% endblock content %}

pmt_act/templates/pmt_act/new_tw.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2 class='animated 1 fadeInUp delay-0s'>Add a new Training/Workshop:</h2>
{% endblock header %}

{% block content %}
				
	<form action="{% url 'pmt_act:new_tw' %}" method='post' class="form animated 1 fadeIn delay-1s" enctype="multipart/form-data">
		
		{% csrf_token %}
		{% bootstrap_form form %}
		
		{% buttons %}
			<button name="submit" class="btn btn-primary animated 1 bounceIn delay-2s">Add Training/Workshop</button>
		{% endbuttons %}
	</form>
	
{% endblock content %}

pmt_act/templates/pmt_act/training_workshop.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	{% if detail.valid == True %}
		<h2 class='animated 1 fadeInUp delay-0s'>Training/Workshop: {{ detail.name }}</h2>
	{% endif %}
{% endblock header %}

{% block content %}
	{% if detail.valid == True %}
	
		<h2 class='animated 1 fadeIn delay-1s' style="color: rgb(255, 102, 0);">Details:</h2>
		<div class="panel panel-default animated 1 fadeIn delay-1s">
			<div class="panel-heading animated 1 fadeIn delay-1s">
				<h3 class='animated 1 fadeIn delay-1s' style="color: rgb(255, 255, 77);">
					Date Added: {{ detail.date_added|date:'M d Y, H:i' }}
					<small>
						{% if user == detail.owner %}
							{% buttons %}
								<a href="{% url 'pmt_act:edit_tw' detail.id %}">
									<button type="button" class="btn btn-primary animated 1 bounceIn delay-2s">EDIT</button>
								</a>
								<a href="{% url 'pmt_act:delete_tw' detail.id %}">
									<button type="button" class="btn btn-primary animated 1 bounceIn delay-2s">DELETE</button>
								</a>
							{% endbuttons %}
						{% endif %}
					</small>
				</h3>
			</div>
			<div class="panel-body animated 1 zoomIn delay-1s">
				<img src='/assets/{{ detail.banner }}' width='300vw' height='200vh' align="right">
				Registration Begins: {{ detail.registration_Begins|date:'M d Y, H:i' }}</br>
				Registration Ends: {{ detail.registration_Ends|date:'M d Y, H:i' }}</br>
				Event Begins: {{ detail.event_Begins|date:'M d Y, H:i' }}</br>
				Event Fee: {{ detail.event_Fee }}/-</br>
				Event URL: <a href={{ detail.event_URL }}>{{ detail.event_URL }}</a></br>
				Additional Details: {{ detail.additional_Details }}</br>
				Contact Name: {{ detail.contact_Name }}</br>
				Contact E-Mail: {{ detail.contact_Email }}</br>
				Contact No.: {{ detail.contact_No }}</br>
				 Document: <a href='/assets/{{ detail.document }}'>
					{% if detail.document %}
						Click to download
					{% endif %}
				</a>
				
			</div>
		</div>
		
		
		<form action="{% url 'pmt_act:enroll_tw' detail.id %}" method='post' class="form animated 1 fadeIn delay-2s" enctype="multipart/form-data">
			
			{% csrf_token %}
		
				{% buttons %}
					<button type='submit' name="enroll" class="btn btn-primary animated 1 bounceIn delay-2s">{{ enroll_tw.user_id_id }}ENROLL</button>
				{% endbuttons %}
				
		</form>
		<div class="animated 1 fadeIn delay-2s">Number of already enrolled users: {{ count }}</div>
		
	{% endif %}
{% endblock content %}

pmt_act/templates/pmt_act/trainings_workshops.html
{% extends "pmt_act/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2 class='animated 1 fadeInUp delay-0s'>Trainings/Workshops</h2>
{% endblock header %}

{% block content %}
	
	<div class="panel panel-default animated 1 fadeIn delay-0s">
		{% for training_workshop in trainings_workshops %}
			{% if training_workshop.valid == True %}
				<div class="panel-heading animated 1 fadeIn delay-1s">
					<a href="{% url 'pmt_act:training_workshop' training_workshop.id %}">
						<h3>
							{{ training_workshop }} 
						</h3>
					</a>
				</div>
				</br>
			{% endif %}
		{% empty %}
			<h3 class='animated 1 fadeIn delay-1s'>No training/workshop have been added yet.</h3>
		{% endfor %}
	</div>
	
	<h3>
		<a href="{% url 'pmt_act:new_tw' %}">
			{% buttons %}
				<button type="button" class="btn btn-primary animated 1 bounceIn delay-2s">Add New Training/Workshop</button>
			{% endbuttons %}
		</a>
	</h3>

{% endblock content %}